version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openssh-client
      - gem install bundler
      - tar xzvf package/simple-env-*.tgz

  pre_build:
    commands:
      - make plan

  build:
    commands:
      - make up
      - make test

  post_build:
    commands:
      - make destroy
